/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_wrappers_pb = require('google-protobuf/google/protobuf/wrappers_pb.js');
var google_protobuf_empty_pb = require('google-protobuf/google/protobuf/empty_pb.js');
goog.exportSymbol('proto.com.bht.saigonparking.api.grpc.user.Customer', null, global);
goog.exportSymbol('proto.com.bht.saigonparking.api.grpc.user.ParkingLotEmployee', null, global);
goog.exportSymbol('proto.com.bht.saigonparking.api.grpc.user.User', null, global);
goog.exportSymbol('proto.com.bht.saigonparking.api.grpc.user.UserRole', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.bht.saigonparking.api.grpc.user.User = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.bht.saigonparking.api.grpc.user.User, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.com.bht.saigonparking.api.grpc.user.User.displayName = 'proto.com.bht.saigonparking.api.grpc.user.User';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.bht.saigonparking.api.grpc.user.User.prototype.toObject = function(opt_includeInstance) {
  return proto.com.bht.saigonparking.api.grpc.user.User.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.bht.saigonparking.api.grpc.user.User} msg The msg instance to transform.
 * @return {!Object}
 */
proto.com.bht.saigonparking.api.grpc.user.User.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: msg.getId(),
    role: msg.getRole(),
    username: msg.getUsername(),
    password: msg.getPassword(),
    email: msg.getEmail(),
    isactivated: msg.getIsactivated(),
    lastsignin: msg.getLastsignin(),
    version: msg.getVersion()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.com.bht.saigonparking.api.grpc.user.User} The clone.
 */
proto.com.bht.saigonparking.api.grpc.user.User.prototype.cloneMessage = function() {
  return /** @type {!proto.com.bht.saigonparking.api.grpc.user.User} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional int64 id = 1;
 * @return {number}
 */
proto.com.bht.saigonparking.api.grpc.user.User.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 1, 0));
};


/** @param {number} value  */
proto.com.bht.saigonparking.api.grpc.user.User.prototype.setId = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional UserRole role = 2;
 * @return {!proto.com.bht.saigonparking.api.grpc.user.UserRole}
 */
proto.com.bht.saigonparking.api.grpc.user.User.prototype.getRole = function() {
  return /** @type {!proto.com.bht.saigonparking.api.grpc.user.UserRole} */ (jspb.Message.getFieldProto3(this, 2, 0));
};


/** @param {!proto.com.bht.saigonparking.api.grpc.user.UserRole} value  */
proto.com.bht.saigonparking.api.grpc.user.User.prototype.setRole = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional string username = 3;
 * @return {string}
 */
proto.com.bht.saigonparking.api.grpc.user.User.prototype.getUsername = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 3, ""));
};


/** @param {string} value  */
proto.com.bht.saigonparking.api.grpc.user.User.prototype.setUsername = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * optional string password = 4;
 * @return {string}
 */
proto.com.bht.saigonparking.api.grpc.user.User.prototype.getPassword = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 4, ""));
};


/** @param {string} value  */
proto.com.bht.saigonparking.api.grpc.user.User.prototype.setPassword = function(value) {
  jspb.Message.setField(this, 4, value);
};


/**
 * optional string email = 5;
 * @return {string}
 */
proto.com.bht.saigonparking.api.grpc.user.User.prototype.getEmail = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 5, ""));
};


/** @param {string} value  */
proto.com.bht.saigonparking.api.grpc.user.User.prototype.setEmail = function(value) {
  jspb.Message.setField(this, 5, value);
};


/**
 * optional bool isActivated = 6;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.com.bht.saigonparking.api.grpc.user.User.prototype.getIsactivated = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldProto3(this, 6, false));
};


/** @param {boolean} value  */
proto.com.bht.saigonparking.api.grpc.user.User.prototype.setIsactivated = function(value) {
  jspb.Message.setField(this, 6, value);
};


/**
 * optional string lastSignIn = 7;
 * @return {string}
 */
proto.com.bht.saigonparking.api.grpc.user.User.prototype.getLastsignin = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 7, ""));
};


/** @param {string} value  */
proto.com.bht.saigonparking.api.grpc.user.User.prototype.setLastsignin = function(value) {
  jspb.Message.setField(this, 7, value);
};


/**
 * optional int64 version = 8;
 * @return {number}
 */
proto.com.bht.saigonparking.api.grpc.user.User.prototype.getVersion = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 8, 0));
};


/** @param {number} value  */
proto.com.bht.saigonparking.api.grpc.user.User.prototype.setVersion = function(value) {
  jspb.Message.setField(this, 8, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.bht.saigonparking.api.grpc.user.Customer = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.bht.saigonparking.api.grpc.user.Customer, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.com.bht.saigonparking.api.grpc.user.Customer.displayName = 'proto.com.bht.saigonparking.api.grpc.user.Customer';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.bht.saigonparking.api.grpc.user.Customer.prototype.toObject = function(opt_includeInstance) {
  return proto.com.bht.saigonparking.api.grpc.user.Customer.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.bht.saigonparking.api.grpc.user.Customer} msg The msg instance to transform.
 * @return {!Object}
 */
proto.com.bht.saigonparking.api.grpc.user.Customer.toObject = function(includeInstance, msg) {
  var f, obj = {
    userinfo: (f = msg.getUserinfo()) && proto.com.bht.saigonparking.api.grpc.user.User.toObject(includeInstance, f),
    firstname: msg.getFirstname(),
    lastname: msg.getLastname(),
    phone: msg.getPhone(),
    lastupdated: msg.getLastupdated()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.com.bht.saigonparking.api.grpc.user.Customer} The clone.
 */
proto.com.bht.saigonparking.api.grpc.user.Customer.prototype.cloneMessage = function() {
  return /** @type {!proto.com.bht.saigonparking.api.grpc.user.Customer} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional User userInfo = 1;
 * @return {proto.com.bht.saigonparking.api.grpc.user.User}
 */
proto.com.bht.saigonparking.api.grpc.user.Customer.prototype.getUserinfo = function() {
  return /** @type{proto.com.bht.saigonparking.api.grpc.user.User} */ (
    jspb.Message.getWrapperField(this, proto.com.bht.saigonparking.api.grpc.user.User, 1));
};


/** @param {proto.com.bht.saigonparking.api.grpc.user.User|undefined} value  */
proto.com.bht.saigonparking.api.grpc.user.Customer.prototype.setUserinfo = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.com.bht.saigonparking.api.grpc.user.Customer.prototype.clearUserinfo = function() {
  this.setUserinfo(undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.com.bht.saigonparking.api.grpc.user.Customer.prototype.hasUserinfo = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string firstName = 2;
 * @return {string}
 */
proto.com.bht.saigonparking.api.grpc.user.Customer.prototype.getFirstname = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 2, ""));
};


/** @param {string} value  */
proto.com.bht.saigonparking.api.grpc.user.Customer.prototype.setFirstname = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional string lastName = 3;
 * @return {string}
 */
proto.com.bht.saigonparking.api.grpc.user.Customer.prototype.getLastname = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 3, ""));
};


/** @param {string} value  */
proto.com.bht.saigonparking.api.grpc.user.Customer.prototype.setLastname = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * optional string phone = 4;
 * @return {string}
 */
proto.com.bht.saigonparking.api.grpc.user.Customer.prototype.getPhone = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 4, ""));
};


/** @param {string} value  */
proto.com.bht.saigonparking.api.grpc.user.Customer.prototype.setPhone = function(value) {
  jspb.Message.setField(this, 4, value);
};


/**
 * optional string lastUpdated = 5;
 * @return {string}
 */
proto.com.bht.saigonparking.api.grpc.user.Customer.prototype.getLastupdated = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 5, ""));
};


/** @param {string} value  */
proto.com.bht.saigonparking.api.grpc.user.Customer.prototype.setLastupdated = function(value) {
  jspb.Message.setField(this, 5, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.bht.saigonparking.api.grpc.user.ParkingLotEmployee = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.bht.saigonparking.api.grpc.user.ParkingLotEmployee, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.com.bht.saigonparking.api.grpc.user.ParkingLotEmployee.displayName = 'proto.com.bht.saigonparking.api.grpc.user.ParkingLotEmployee';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.bht.saigonparking.api.grpc.user.ParkingLotEmployee.prototype.toObject = function(opt_includeInstance) {
  return proto.com.bht.saigonparking.api.grpc.user.ParkingLotEmployee.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.bht.saigonparking.api.grpc.user.ParkingLotEmployee} msg The msg instance to transform.
 * @return {!Object}
 */
proto.com.bht.saigonparking.api.grpc.user.ParkingLotEmployee.toObject = function(includeInstance, msg) {
  var f, obj = {
    userinfo: (f = msg.getUserinfo()) && proto.com.bht.saigonparking.api.grpc.user.User.toObject(includeInstance, f),
    parkinglotid: msg.getParkinglotid()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.com.bht.saigonparking.api.grpc.user.ParkingLotEmployee} The clone.
 */
proto.com.bht.saigonparking.api.grpc.user.ParkingLotEmployee.prototype.cloneMessage = function() {
  return /** @type {!proto.com.bht.saigonparking.api.grpc.user.ParkingLotEmployee} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional User userInfo = 1;
 * @return {proto.com.bht.saigonparking.api.grpc.user.User}
 */
proto.com.bht.saigonparking.api.grpc.user.ParkingLotEmployee.prototype.getUserinfo = function() {
  return /** @type{proto.com.bht.saigonparking.api.grpc.user.User} */ (
    jspb.Message.getWrapperField(this, proto.com.bht.saigonparking.api.grpc.user.User, 1));
};


/** @param {proto.com.bht.saigonparking.api.grpc.user.User|undefined} value  */
proto.com.bht.saigonparking.api.grpc.user.ParkingLotEmployee.prototype.setUserinfo = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.com.bht.saigonparking.api.grpc.user.ParkingLotEmployee.prototype.clearUserinfo = function() {
  this.setUserinfo(undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.com.bht.saigonparking.api.grpc.user.ParkingLotEmployee.prototype.hasUserinfo = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional int64 parkingLotId = 2;
 * @return {number}
 */
proto.com.bht.saigonparking.api.grpc.user.ParkingLotEmployee.prototype.getParkinglotid = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 2, 0));
};


/** @param {number} value  */
proto.com.bht.saigonparking.api.grpc.user.ParkingLotEmployee.prototype.setParkinglotid = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * @enum {number}
 */
proto.com.bht.saigonparking.api.grpc.user.UserRole = {
  CUSTOMER: 0,
  PARKING_LOT_EMPLOYEE: 1,
  GOVERNMENT_EMPLOYEE: 2,
  ADMIN: 3
};

goog.object.extend(exports, proto.com.bht.saigonparking.api.grpc.user);
